name: Build And Test
run-name: ${{ github.actor }} is runs ci pipeline
on:
  push:
    branches:
      - main
    paths-ignore:
      - LICENCE
      - 'docs/**'
      - 'helm/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: ./Dockerfile
#          platforms: linux/amd64
#          push: true
#          tags: gnu96/github-docker-build-push-repo:latest