name: Build And Test
run-name: ${{ gitea.actor }} is runs ci pipeline
on:
  push:
    branches:
      - main
    paths-ignore:
      - LICENCE
      - 'docs/**'
      - 'helm/**'

jobs:
  Gitea-Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: gnu96/gitea-docker-build-push-repo:latest